import {
  Inter_400Regular,
  Inter_500Medium,
  Inter_600SemiBold,
  Inter_700Bold,
  useFonts,
} from "@expo-google-fonts/inter";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Stack, useRouter, useSegments } from "expo-router";
import * as SplashScreen from "expo-splash-screen";
import React, { useEffect } from "react";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { KeyboardProvider } from "react-native-keyboard-controller";
import { SafeAreaProvider } from "react-native-safe-area-context";

import { ErrorBoundary } from "@/components/ErrorBoundary";
import { AppProvider, useApp } from "@/context/AppContext";
import { ThemeProvider } from "@/context/ThemeContext";
import {
  WhatsAppIntegrationProvider,
  registerNotificationHandler,
} from "@/context/WhatsAppIntegrationProvider";
import { BootstrapGate } from "@/components/BootstrapGate";
import { ColdStartOverlay } from "@/components/ColdStartOverlay";
import { bootstrapApp } from "@/services/appBootstrapService";

// ─── Register notification display handler at module load time ────────────────
// Must be called OUTSIDE of any component to take effect before the first render.
registerNotificationHandler();

SplashScreen.preventAutoHideAsync();

const queryClient = new QueryClient();

function AuthGuard() {
  const { currentUser, loading } = useApp();
  const segments = useSegments();
  const router = useRouter();

  useEffect(() => {
    if (loading) return;

    const inAuthGroup = segments[0] === "login" || segments[0] === "forgot-password";
    // @ts-expect-error Types generated by Expo Router dynamically
    const inCompleteProfile = segments[0] === "complete-profile";

    if (!currentUser) {
      if (!inAuthGroup) {
        router.replace("/login");
      }
    } else {
      if (inAuthGroup) {
        // If we are logged in, we shouldn't be in the login group.
        // If they are in complete-profile, let them stay there until they finish.
        router.replace("/(tabs)");
      }
    }
  }, [currentUser, loading, segments]);

  return null;
}

function RootStack() {
  return (
    <>
      <AuthGuard />
      <Stack screenOptions={{ headerShown: false }}>
        <Stack.Screen name="index" options={{ headerShown: false }} />
        <Stack.Screen name="login" options={{ headerShown: false }} />
        <Stack.Screen name="complete-profile" options={{ headerShown: false, gestureEnabled: false }} />
        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        <Stack.Screen name="task/[id]" options={{ headerShown: false, presentation: "card" }} />
        <Stack.Screen name="member/[id]" options={{ headerShown: false, presentation: "card" }} />
        <Stack.Screen name="+not-found" />
      </Stack>
    </>
  );
}

export default function RootLayout() {
  const [fontsLoaded, fontError] = useFonts({
    Inter_400Regular,
    Inter_500Medium,
    Inter_600SemiBold,
    Inter_700Bold,
  });
  const [startupReady, setStartupReady] = React.useState(false);

  useEffect(() => {
    if (!fontsLoaded && !fontError) return;

    let cancelled = false;
    bootstrapApp()
      .then(() => {
        if (!cancelled) setStartupReady(true);
      })
      .catch(() => {
        if (!cancelled) setStartupReady(true);
      });

    return () => {
      cancelled = true;
    };
  }, [fontsLoaded, fontError]);

  useEffect(() => {
    if (startupReady && (fontsLoaded || fontError)) {
      SplashScreen.hideAsync();
    }
  }, [startupReady, fontsLoaded, fontError]);

  if (!fontsLoaded && !fontError) return null;
  if (!startupReady) return null;

  return (
    <SafeAreaProvider>
      <ErrorBoundary>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider>
            <BootstrapGate>
            <AppProvider>
              {/* WhatsAppIntegrationProvider must live inside AppProvider so it
                  can access auth state if needed in future, but outside the
                  navigation stack so it persists across all routes. */}
              <WhatsAppIntegrationProvider>
                <GestureHandlerRootView style={{ flex: 1 }}>
                  <KeyboardProvider>
                    <RootStack />
                  </KeyboardProvider>
                </GestureHandlerRootView>
                <ColdStartOverlay />
              </WhatsAppIntegrationProvider>
            </AppProvider>
            </BootstrapGate>
          </ThemeProvider>
        </QueryClientProvider>
      </ErrorBoundary>
    </SafeAreaProvider>
  );
}
